### pH and Chl-a

for each cluster identified by pH cluster analysis show  alongside chl-a

```{r ph_with_chla}
if (opt_category == "bgc_ph_ph" | opt_category == "bgc_ph_h_plus") {

  # Read chl-a data and link to cluster ID
  chla_bgc_va <- read_rds(file = paste0(path_argo_preprocessed, "/chla_bgc_va.rds"))
  chla_cluster <-
    full_join(
      chla_bgc_va,
      anomaly_cluster_all %>% distinct (file_id, cluster, profile_type, num_clusters)
    ) %>% filter(!is.na(cluster))

  # summarise by cluster
  chla_cluster_mean <- chla_cluster %>%
    group_by(cluster, profile_type, num_clusters, depth) %>%
    summarise(
      chla_mean = mean(chla, na.rm = TRUE),
      chla_sd = sd(chla, na.rm = TRUE)
    ) %>%
    ungroup() %>%
    select(
      cluster,
      profile_type,
      num_clusters,
      chla_depth = depth,
      chla_mean,
      chla_sd
    )

  # join pH anomaly with chl-a
  cluster_ph_chla <- full_join(anomaly_cluster_mean, chla_cluster_mean)
  chla_color <- "#69b3a2"

  if (opt_category == "bgc_ph_ph"){
    chla_to_ph_factor <- 25
    chla_to_ph_offset <- 1
  } else {
    chla_to_ph_factor <- 1e9
    chla_to_ph_offset <- 1
  }

  # Add the cluster count information
  cluster_ph_chla <- left_join(cluster_ph_chla, cluster_count)

  cluster_ph_chla %>% 
    filter (profile_type == "base") %>%
    group_split(profile_type, num_clusters) %>%
    map(
    ~ ggplot(data = .x,) +
      geom_path(aes(x = anomaly_mean,
                    y = depth)) +
      geom_ribbon(aes(
        xmax = anomaly_mean + anomaly_sd,
        xmin = anomaly_mean - anomaly_sd,
        y = depth
      ),
      alpha = 0.2) +
      geom_path(aes(
        x = (chla_mean - chla_to_ph_offset) / chla_to_ph_factor,
        y = chla_depth
      ), color = chla_color) +
      geom_ribbon(
        aes(
          xmax = (chla_mean + chla_sd - chla_to_ph_offset) / chla_to_ph_factor,
          xmin = (chla_mean - chla_sd - chla_to_ph_offset) / chla_to_ph_factor,
          y = chla_depth
        ),
        fill = chla_color,
        alpha = 0.2
      ) +
      geom_vline(xintercept = 0) +
      scale_y_continuous(trans = trans_reverser("sqrt"),
                         breaks = c(10, 100, 250, 500, seq(1000, 5000, 500))) +
      facet_wrap(~ paste0(cluster, " (", formatC(count_profiles, big.mark=",") , ")"),
                  strip.position = "right") +
      coord_cartesian(xlim = opt_xlim) +
      scale_x_continuous(
        # First axis
        name = opt_measure_label,
        breaks = opt_xbreaks,
        # Second axis
        sec.axis = sec_axis(
          trans =  ~ . * chla_to_ph_factor + chla_to_ph_offset,
          name = opt_chla_measure_label
        )
      ) +
      labs(
        title = paste0(
          'Overall mean anomaly profiles by cluster \n',
          'type = ', unique(.x$profile_type), ', ', 
          'num clusters = ', unique(.x$num_clusters)
        ),
        x = opt_measure_label,
        y = 'depth (m)'
      ) +
      theme(axis.title.x.top = element_text(color = chla_color),
            axis.text.x.top = element_text(color = chla_color))
    )

}

```

Adjusted profiles

```{r ph_with_chla_adj}
if (opt_category == "bgc_ph_ph" | opt_category == "bgc_ph_h_plus") {
  
  if (opt_category == "bgc_ph_ph"){
    chla_to_ph_factor <- 1
    chla_to_ph_offset <- 0.5
  } else {
    chla_to_ph_factor <- 1
    chla_to_ph_offset <- 0.5
  }
  
  cluster_ph_chla %>% 
    filter (profile_type == "adjusted") %>%
    group_split(profile_type, num_clusters) %>%
    map(
    ~ ggplot(data = .x,) +
      geom_path(aes(x = anomaly_mean,
                    y = depth)) +
      geom_ribbon(aes(
        xmax = anomaly_mean + anomaly_sd,
        xmin = anomaly_mean - anomaly_sd,
        y = depth
      ),
      alpha = 0.2) +
      geom_path(aes(
        x = (chla_mean - chla_to_ph_offset) / chla_to_ph_factor,
        y = chla_depth
      ), color = chla_color) +
      geom_ribbon(
        aes(
          xmax = (chla_mean + chla_sd - chla_to_ph_offset) / chla_to_ph_factor,
          xmin = (chla_mean - chla_sd - chla_to_ph_offset) / chla_to_ph_factor,
          y = chla_depth
        ),
        fill = chla_color,
        alpha = 0.2
      ) +
      geom_vline(xintercept = 0) +
      scale_y_continuous(trans = trans_reverser("sqrt"),
                         breaks = c(10, 100, 250, 500, seq(1000, 5000, 500))) +
      facet_wrap(~ paste0(cluster, " (", formatC(count_profiles, big.mark=",") , ")"),
                  strip.position = "right") +
      coord_cartesian(xlim = opt_xlim_adjusted) +
      scale_x_continuous(
        # First axis
        name = opt_measure_label_adjusted,
        breaks = opt_xbreaks_adjusted,
        # Second axis
        sec.axis = sec_axis(
          trans =  ~ . * chla_to_ph_factor + chla_to_ph_offset,
          name = opt_chla_measure_label
        )
      ) +
      labs(
        title = paste0(
          'Overall mean anomaly profiles by cluster \n',
          'type = ', unique(.x$profile_type), ', ', 
          'num clusters = ', unique(.x$num_clusters)
        ),
        x = opt_measure_label_adjusted,
        y = 'depth (m)'
      ) +
      theme(axis.title.x.top = element_text(color = chla_color),
            axis.text.x.top = element_text(color = chla_color))
    )

}

```

### pH and oxygen anomaly

for each cluster identified by pH cluster analysis show alongside oxygen anomaly

```{r ph_with_oxygen}
if (opt_category == "bgc_ph_ph" | opt_category == "bgc_ph_h_plus") {
  
  # Read oxygen anomaly data and link to cluster information
  doxy_bgc_va <- read_rds(file = paste0(path_argo_preprocessed, "/doxy_anomaly_va.rds"))
  doxy_cluster <-
    full_join(
      doxy_bgc_va,
      anomaly_cluster_all %>% distinct (file_id, cluster, profile_type, num_clusters)
    ) %>% filter(!is.na(cluster))
  
  # summarise by cluster, , profile_type, num_clusters
  doxy_cluster_mean <- doxy_cluster %>%
    group_by(cluster, profile_type, num_clusters, depth) %>%
    summarise(
      doxy_anomaly_mean = mean(anomaly, na.rm = TRUE),
      doxy_anomaly_sd = sd(anomaly, na.rm = TRUE)
    ) %>%
    ungroup() %>%
    select(
      cluster,
      profile_type,
      num_clusters,
      doxy_depth = depth,
      doxy_anomaly_mean,
      doxy_anomaly_sd
    )
  

  # join pH anomaly with oxygen
  #anomaly_cluster_mean
  cluster_ph_doxy <- full_join(anomaly_cluster_mean, doxy_cluster_mean)
  doxy_color <- "#5B9BD5"

  if (opt_category == "bgc_ph_ph"){
    doxy_to_ph_factor <- 250
    doxy_to_ph_offset <- 0
  } else {
    doxy_to_ph_factor <- 1e10
    doxy_to_ph_offset <- 0
  }

  # Add the cluster count information
  cluster_ph_doxy <- left_join(cluster_ph_doxy, cluster_count)
    
  cluster_ph_doxy %>%
    filter (profile_type == "base") %>%
    group_split(profile_type, num_clusters) %>%
    map(
    ~ ggplot(data = .x,) +
      geom_path(aes(x = anomaly_mean,
                    y = depth)) +
      geom_ribbon(aes(
        xmax = anomaly_mean + anomaly_sd,
        xmin = anomaly_mean - anomaly_sd,
        y = depth
      ),
      alpha = 0.2) +
      geom_path(aes(
        x = (doxy_anomaly_mean - doxy_to_ph_offset)  / doxy_to_ph_factor,
        y = doxy_depth
      ), color = doxy_color) +
      geom_ribbon(
        aes(
          xmax = (doxy_anomaly_mean + doxy_anomaly_sd - doxy_to_ph_offset) / doxy_to_ph_factor,
          xmin = (doxy_anomaly_mean - doxy_anomaly_sd - doxy_to_ph_offset) / doxy_to_ph_factor,
          y = doxy_depth
        ),
        fill = doxy_color,
        alpha = 0.2
      ) +
      geom_vline(xintercept = 0) +
      scale_y_reverse() +
      facet_wrap(~ paste0(cluster, " (", formatC(count_profiles, big.mark=",") , ")"),
                  strip.position = "right") +
      coord_cartesian(xlim = opt_xlim) +
      scale_x_continuous(
        # First axis
        name = opt_measure_label,
        breaks = opt_xbreaks,
        # First axis
        sec.axis = sec_axis(
          trans =  ~ . * doxy_to_ph_factor + doxy_to_ph_offset,
          name = opt_doxy_measure_label
        )
      ) +
      labs(        
        title = paste0(
          'Overall mean anomaly profiles by cluster \n',
          'type = ', unique(.x$profile_type), ', ', 
          'num clusters = ', unique(.x$num_clusters)
        ),
        x = opt_measure_label, 
        y = 'depth (m)'
        ) +
      theme(axis.title.x.top = element_text(color = doxy_color),
            axis.text.x.top = element_text(color = doxy_color))
    )
  
}

```

Adjusted profiles

```{r ph_with_oxygen_adj}

if (opt_category == "bgc_ph_ph" | opt_category == "bgc_ph_h_plus") {

  if (opt_category == "bgc_ph_ph"){
    doxy_to_ph_factor <- 20
    doxy_to_ph_offset <- 0
  } else {
    doxy_to_ph_factor <- 20
    doxy_to_ph_offset <- 0
  }
  
  cluster_ph_doxy %>%
    filter (profile_type == "adjusted") %>%
    group_split(profile_type, num_clusters) %>%
    map(
    ~ ggplot(data = .x,) +
      geom_path(aes(x = anomaly_mean,
                    y = depth)) +
      geom_ribbon(aes(
        xmax = anomaly_mean + anomaly_sd,
        xmin = anomaly_mean - anomaly_sd,
        y = depth
      ),
      alpha = 0.2) +
      geom_path(aes(
        x = (doxy_anomaly_mean - doxy_to_ph_offset)  / doxy_to_ph_factor,
        y = doxy_depth
      ), color = doxy_color) +
      geom_ribbon(
        aes(
          xmax = (doxy_anomaly_mean + doxy_anomaly_sd - doxy_to_ph_offset) / doxy_to_ph_factor,
          xmin = (doxy_anomaly_mean - doxy_anomaly_sd - doxy_to_ph_offset) / doxy_to_ph_factor,
          y = doxy_depth
        ),
        fill = doxy_color,
        alpha = 0.2
      ) +
      geom_vline(xintercept = 0) +
      scale_y_reverse() +
      facet_wrap(~ paste0(cluster, " (", formatC(count_profiles, big.mark=",") , ")"),
                  strip.position = "right") +
      coord_cartesian(xlim = opt_xlim_adjusted) +
      scale_x_continuous(
        # First axis
        name = opt_measure_label_adjusted,
        breaks = opt_xbreaks_adjusted,
        # First axis
        sec.axis = sec_axis(
          trans =  ~ . * doxy_to_ph_factor + doxy_to_ph_offset,
          name = opt_doxy_measure_label
        )
      ) +
      labs(        
        title = paste0(
          'Overall mean anomaly profiles by cluster \n',
          'type = ', unique(.x$profile_type), ', ', 
          'num clusters = ', unique(.x$num_clusters)
        ),
        x = opt_measure_label_adjusted, 
        y = 'depth (m)'
        ) +
      theme(axis.title.x.top = element_text(color = doxy_color),
            axis.text.x.top = element_text(color = doxy_color))
    )
  
}

```

### pH and nitrate anomaly

for each cluster identified by pH cluster analysis show alongside nitrate anomaly

```{r ph_with_nitrate}
if (opt_category == "bgc_ph_ph" | opt_category == "bgc_ph_h_plus") {
  
  # Read oxygen anomaly data and link to cluster information
  nitrate_bgc_va <- read_rds(file = paste0(path_argo_preprocessed, "/nitrate_anomaly_va.rds"))
  nitrate_cluster <-
    full_join(
      nitrate_bgc_va,
      anomaly_cluster_all %>% distinct (file_id, cluster, profile_type, num_clusters)
    ) %>% filter(!is.na(cluster))
  
  # summarise by cluster, , profile_type, num_clusters
  nitrate_cluster_mean <- nitrate_cluster %>%
    group_by(cluster, profile_type, num_clusters, depth) %>%
    summarise(
      nitrate_anomaly_mean = mean(anomaly, na.rm = TRUE),
      nitrate_anomaly_sd = sd(anomaly, na.rm = TRUE)
    ) %>%
    ungroup() %>%
    select(
      cluster,
      profile_type,
      num_clusters,
      nitrate_depth = depth,
      nitrate_anomaly_mean,
      nitrate_anomaly_sd
    )
  

  # join pH anomaly with nitrate
  #anomaly_cluster_mean
  cluster_ph_nitrate <- full_join(anomaly_cluster_mean, nitrate_cluster_mean)
  nitrate_color <- "#ED7D31"

  if (opt_category == "bgc_ph_ph"){
    nitrate_to_ph_factor <- 75
    nitrate_to_ph_offset <- 0
  } else {
    nitrate_to_ph_factor <- 3e9
    nitrate_to_ph_offset <- 0
  }
  
  # Add the cluster count information
  cluster_ph_nitrate <- left_join(cluster_ph_nitrate, cluster_count)
    
  cluster_ph_nitrate %>%
    filter (profile_type == "base") %>%
    group_split(profile_type, num_clusters) %>%
    map(
    ~ ggplot(data = .x,) +
      geom_path(aes(x = anomaly_mean,
                    y = depth)) +
      geom_ribbon(aes(
        xmax = anomaly_mean + anomaly_sd,
        xmin = anomaly_mean - anomaly_sd,
        y = depth
      ),
      alpha = 0.2) +
      geom_path(aes(
        x = (nitrate_anomaly_mean - nitrate_to_ph_offset)  / nitrate_to_ph_factor,
        y = nitrate_depth
      ), color = nitrate_color) +
      geom_ribbon(
        aes(
          xmax = (nitrate_anomaly_mean + nitrate_anomaly_sd - nitrate_to_ph_offset) / nitrate_to_ph_factor,
          xmin = (nitrate_anomaly_mean - nitrate_anomaly_sd - nitrate_to_ph_offset) / nitrate_to_ph_factor,
          y = nitrate_depth
        ),
        fill = nitrate_color,
        alpha = 0.2
      ) +
      geom_vline(xintercept = 0) +
      scale_y_reverse() +
      facet_wrap(~ paste0(cluster, " (", formatC(count_profiles, big.mark=",") , ")"),
                  strip.position = "right") +
      coord_cartesian(xlim = opt_xlim) +
      scale_x_continuous(
        # First axis
        name = opt_measure_label,
        breaks = opt_xbreaks,
        # First axis
        sec.axis = sec_axis(
          trans =  ~ . * nitrate_to_ph_factor + nitrate_to_ph_offset,
          name = opt_nitrate_measure_label
        )
      ) +
      labs(        
        title = paste0(
          'Overall mean anomaly profiles by cluster \n',
          'type = ', unique(.x$profile_type), ', ', 
          'num clusters = ', unique(.x$num_clusters)
        ),
        x = opt_measure_label, 
        y = 'depth (m)'
        ) +
      theme(axis.title.x.top = element_text(color = nitrate_color),
            axis.text.x.top = element_text(color = nitrate_color))
    )
  
}

```

Adjusted profiles

```{r ph_with_nitrate_adj}

if (opt_category == "bgc_ph_ph" | opt_category == "bgc_ph_h_plus") {

  if (opt_category == "bgc_ph_ph"){
    nitrate_to_ph_factor <- 6
    nitrate_to_ph_offset <- 0
  } else {
    nitrate_to_ph_factor <- 6
    nitrate_to_ph_offset <- 0
  }
  
  cluster_ph_nitrate %>%
    filter (profile_type == "adjusted") %>%
    group_split(profile_type, num_clusters) %>%
    map(
    ~ ggplot(data = .x,) +
      geom_path(aes(x = anomaly_mean,
                    y = depth)) +
      geom_ribbon(aes(
        xmax = anomaly_mean + anomaly_sd,
        xmin = anomaly_mean - anomaly_sd,
        y = depth
      ),
      alpha = 0.2) +
      geom_path(aes(
        x = (nitrate_anomaly_mean - nitrate_to_ph_offset)  / nitrate_to_ph_factor,
        y = nitrate_depth
      ), color = nitrate_color) +
      geom_ribbon(
        aes(
          xmax = (nitrate_anomaly_mean + nitrate_anomaly_sd - nitrate_to_ph_offset) / nitrate_to_ph_factor,
          xmin = (nitrate_anomaly_mean - nitrate_anomaly_sd - nitrate_to_ph_offset) / nitrate_to_ph_factor,
          y = nitrate_depth
        ),
        fill = nitrate_color,
        alpha = 0.2
      ) +
      geom_vline(xintercept = 0) +
      scale_y_reverse() +
      facet_wrap(~ paste0(cluster, " (", formatC(count_profiles, big.mark=",") , ")"),
                  strip.position = "right") +
      coord_cartesian(xlim = opt_xlim_adjusted) +
      scale_x_continuous(
        # First axis
        name = opt_measure_label_adjusted,
        breaks = opt_xbreaks_adjusted,
        # First axis
        sec.axis = sec_axis(
          trans =  ~ . * nitrate_to_ph_factor + nitrate_to_ph_offset,
          name = opt_nitrate_measure_label
        )
      ) +
      labs(        
        title = paste0(
          'Overall mean anomaly profiles by cluster \n',
          'type = ', unique(.x$profile_type), ', ', 
          'num clusters = ', unique(.x$num_clusters)
        ),
        x = opt_measure_label_adjusted, 
        y = 'depth (m)'
        ) +
      theme(axis.title.x.top = element_text(color = nitrate_color),
            axis.text.x.top = element_text(color = nitrate_color))
    )
  
}

```
