---
title: " Load OceanSODA data"
author: "Pasqualina Vonlanthen & Jens Daniel Müller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r set_options_global, include=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```

# Task 

Load in OceanSODA surface pH and SST data 

```{r load_libraries, include=FALSE}

library(tidyverse)
library(lubridate)

```


```{r set_updata_root_directory, include=FALSE}

path_argo <- '/nfs/kryo/work/updata/bgc_argo_r_argodata'
path_updata <- '/nfs/kryo/work/updata'
path_argo_preprocessed <- paste0(path_argo, "/preprocessed_bgc_data")

path_updata <- '/net/kryo/work/datasets/gridded/ocean/2d/observation/pco2/oceansoda_gregor'
path_argo <- '/nfs/kryo/work/datasets/ungridded/3d/ocean/floats/bgc_argo'
# /nfs/kryo/work/datasets/ungridded/3d/ocean/floats/bgc_argo/preprocessed_bgc_data
path_argo_preprocessed <- paste0(path_argo, "/preprocessed_bgc_data")

```

# OceanSODA 

## Temperature 

```{r load_oceanSODA_pH}

OceanSODA <-
  tidync::hyper_tibble(paste(
    path_updata,
    "/OceanSODA_ETHZ-v2023.OCADS.01_1982-2022.nc",
    sep = ""
  ))

OceanSODA <- OceanSODA %>% 
  mutate(date = as.Date(time, origin = '1982-01-15'),
         year = year(date)) %>% 
  mutate(lon = if_else(lon < 20, lon + 360, lon)) %>% 
  mutate(
    lat = cut(lat, seq(-90, 90, 1), seq(-89.5, 89.5, 1)),
    lat = as.numeric(as.character(lat)),
    lon = cut(lon, seq(20, 380, 1), seq(20.5, 379.5, 1)),
    lon = as.numeric(as.character(lon))
  ) %>% 
  filter(year >= 1995)

OceanSODA_temp <- OceanSODA %>% 
  select(year, date, lon, lat, temperature)

OceanSODA_temp %>% 
  write_rds(file = paste0(path_argo_preprocessed, '/OceanSODA_temp.rds'))
```

## pH 

```{r load_OceanSODA_temperature}

OceanSODA <- OceanSODA %>% 
  select(year, date, lat, lon, ph_total, ph_total_uncert) 
  
OceanSODA %>% 
  write_rds(file = paste0(path_argo_preprocessed, '/OceanSODA.rds'))

```



