---
title: "Extreme pH Profiles"
author: "Pasqualina Vonlanthen & Jens Daniel Müller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r set_options_global, include=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```

# Task 

Explore double extremes in the temp and pH anomaly fields  

# Load Data 

```{r load_libraries}

library(tidyverse)
library(lubridate)
library(ggnewscale)

```

```{r set_global_theme}

theme_set(theme_bw())

HNL_colors_map <- c('H' = 'red3',
                    'N' = 'gray90',
                    'L' = 'blue3')

```


```{r set_root_directories}

path_argo <- '/nfs/kryo/work/updata/bgc_argo_r_argodata'
path_argo_preprocessed <- paste0(path_argo, "/preprocessed_bgc_data")
path_emlr_utilities <- "/nfs/kryo/work/jenmueller/emlr_cant/utilities/files/"

```

```{r load_data}

map <-
  read_rds(paste(path_emlr_utilities,
                 "map_landmask_WOA18.rds",
                 sep = ""))

pH_extreme <- read_rds(file = paste0(path_argo_preprocessed, "/OceanSODA_pH_anomaly_field.rds"))

temp_extreme <- read_rds(file = paste0(path_argo_preprocessed, "/OceanSODA_SST_anomaly_field.rds"))


# argo pH data (flag A only)
full_argo <- read_rds(file = paste0(path_argo_preprocessed, "/bgc_merge_flag_A.rds"))


# change the date format for compatibility with OceanSODA pH data
full_argo <- full_argo %>%
  mutate(year = year(date),
         month = month(date)) %>%
  mutate(date = ymd(format(date, "%Y-%m-15")))
```

# Anomaly maps

## pH 

```{r pH_anomaly_map}

pH_extreme %>%
  filter(year >= 2013) %>% 
  group_split(month) %>%
  #head(1) %>%
  map(
    ~map +
      geom_tile(data = .x,
                aes(x = lon_raw,
                    y = lat_raw,
                    fill = ph_extreme))+
      scale_fill_manual(values = HNL_colors_map)+
      facet_wrap(~year, ncol = 2)+
      lims(y = c(-85, -32))+
      labs(title = paste('month:', unique(.x$month)),
           fill = 'pH')
  )


```

## SST 

```{r SST_anomaly_map}

temp_extreme %>%
  filter(year >= 2013) %>% 
  group_split(month) %>%
  #head(1) %>%
  map(
    ~map +
      geom_tile(data = .x,
                aes(x = lon_raw,
                    y = lat_raw,
                    fill = temp_extreme))+
      scale_fill_manual(values = HNL_colors_map)+
      facet_wrap(~year, ncol = 2)+
      lims(y = c(-85, -32))+
      labs(title = paste('month:', unique(.x$month)),
           fill = 'pH')
  )

```

# Join data 

```{r join_temp_pH_extremes}

anomaly_field <- full_join(pH_extreme %>% 
                             select(lon_raw, lat_raw, month, year, date, basin_AIP, biome_name, ph_extreme),
                           temp_extreme %>% 
                             select(lon_raw, lat_raw, month, year, date, basin_AIP, biome_name, temp_extreme))

```

```{r}

# chisq.test(anomaly_field$ph_extreme, anomaly_field$temp_extreme, correct = FALSE)

anomaly_field <- anomaly_field %>%
  mutate(
    double_extreme = case_when(
      temp_extreme == 'H' & ph_extreme == 'H' ~ 'warm_HpH',
      temp_extreme == 'L' &
        ph_extreme == 'H' ~ 'cold_HpH',
      temp_extreme == 'H' &
        ph_extreme == 'L' ~ 'warm_LpH',
      temp_extreme == 'L' &
        ph_extreme == 'L' ~ 'cold_LpH',
      temp_extreme == 'H' &
        ph_extreme == 'N' ~ 'warm',
      temp_extreme == 'L' &
        ph_extreme == 'N' ~ 'cold',
      temp_extreme == 'N' &
        ph_extreme == 'H' ~ 'HpH',
      temp_extreme == 'N' &
        ph_extreme == 'L' ~ 'LpH',
      TRUE ~ 'N'
    )
  ) %>%
  mutate(
    double_extreme = fct_relevel(
      double_extreme,
      'warm_HpH',
      'cold_HpH',
      'warm_LpH',
      'cold_LpH',
      'warm',
      'cold',
      'HpH',
      'LpH',
      'N'
    )
  )

```

# Compound extreme maps 

```{r compound_extreme_maps_transparent_color_newscale}

HNL_colors_map_temp <- c('H' = "#CD534CFF",
                    'N' = 'transparent',
                    'L' = "#0073C2FF")

HNL_colors_map_ph <- c('H' = "#868686FF",
                    'N' = 'transparent',
                    'L' = "#EFC000FF")


anomaly_field %>%
  filter(year >= 2013,
         double_extreme != "N") %>%
  group_split(month) %>%
  # head(1) %>%
  map(
    ~ map +
      geom_tile(data = .x,
                aes(
                  x = lon_raw,
                  y = lat_raw,
                  fill = ph_extreme
                )) +
      scale_fill_manual(values = HNL_colors_map_ph) +
      new_scale_fill() +
      geom_tile(data = .x,
                aes(
                  x = lon_raw,
                  y = lat_raw,
                  fill = temp_extreme
                ), alpha = 0.5) +
      scale_fill_manual(values = HNL_colors_map_temp) +
      facet_wrap(~ year, ncol = 2) +
      lims(y = c(-85, -32)) +
      labs(title = paste0('month:', unique(.x$month)))
  )

rm(HNL_colors_map_temp, HNL_colors_map_ph)

```

```{r compound_extreme_maps}

anomaly_field %>% 
  filter(year >= 2013) %>% 
  group_split(month) %>% 
  map(
    ~map+
      geom_tile(data = .x,
                aes(x = lon_raw,
                    y = lat_raw,
                    fill = double_extreme))+
      facet_wrap(~year, ncol = 2)+
      scale_fill_manual(values = c('warm_HpH' = 'brown',
                                   'warm_LpH' = 'yellow',
                                   'cold_HpH' = 'beige',
                                   'cold_LpH' = 'cyan',
                                   'cold' = 'blue',
                                   'warm' = 'red',
                                   'LpH' = 'orange',
                                   'HpH' = 'green',
                                   'N' = NA),
                        na.value = NA)+
      lims(y = c(-85, -32))+
      labs(title = paste0('month:', unique(.x$month)),
           fill = 'double extreme')
  )

```

# Join Argo profile data 

```{r join_argo_data}

anomaly_field <- anomaly_field %>% 
  rename(lat = lat_raw,
         lon = lon_raw) %>% 
  filter(year >= 2013)
  
profile_double_extreme <- inner_join(full_argo %>% 
                                       select(-c(temp_adjusted_error, 
                                                 temp_adjusted_qc,
                                                 ph_in_situ_total_adjusted_error,
                                                 ph_in_situ_total_adjusted_qc,
                                                 profile_temp_qc,
                                                 profile_ph_in_situ_total_qc)),
                                     anomaly_field)

profile_double_extreme <- profile_double_extreme %>% 
  unite('platform_cycle', platform_number:cycle_number, sep = '_', remove = FALSE)
```

```{r anomaly_field_maps_with_argo_locations}

anomaly_field %>% 
  filter(year >= 2013) %>% 
  group_split(month) %>% 
  map(
    ~map+
      geom_tile(data = .x,
                aes(x = lon,
                    y = lat,
                    fill = double_extreme))+
      facet_wrap(~year, ncol = 2)+
      scale_fill_manual(values = c('warm_HpH' = 'brown',
                                   'warm_LpH' = 'yellow',
                                   'cold_HpH' = 'beige',
                                   'cold_LpH' = 'cyan',
                                   'cold' = 'blue',
                                   'warm' = 'red',
                                   'LpH' = 'orange',
                                   'HpH' = 'green',
                                   'N' = NA),
                        na.value = NA)+
      geom_point(data = profile_double_extreme, 
                 aes(x = lon,
                     y = lat),
                 size = 0.2)+
      lims(y = c(-85, -32))+
      labs(title = paste0('month:', unique(.x$month)),
           fill = 'double extreme')
  )


```


# Plot Profiles 

# Raw 

## pH 

```{r plot_raw_pH_profiles}

profile_double_extreme %>% 
  group_split(biome_name, basin_AIP, year) %>% 
  map(
    ~ggplot(data = .x,
            aes(x = ph_in_situ_total_adjusted,
                y = depth,
                group = platform_cycle,
                col = double_extreme))+
      geom_path(data = .x %>% filter(double_extreme == 'N'),
                aes(x = ph_in_situ_total_adjusted,
                    y = depth, 
                    group = platform_cycle,
                    col = double_extreme),
                size = 0.3)+
      geom_path(data = .x %>% filter(double_extreme == 'E'),
                aes(x = ph_in_situ_total_adjusted,
                    y = depth, 
                    group = platform_cycle,
                    col = double_extreme),
                size = 0.5)+
      scale_y_reverse()+
      scale_color_manual(values = c('N' = 'gray', 'E' = 'red'))+
      facet_wrap(~month, ncol = 6)+
      labs(title = paste0('biome: ', unique(.x$biome_name), '| ', unique(.x$basin_AIP), '| ', unique(.x$year)),
           col = 'double extreme',
           x = 'Argo pH',
           y = 'depth')
  )

```

## Temperature 

```{r plot_raw_temperature_profiles_double_extreme}

profile_double_extreme %>% 
  group_split(biome_name, basin_AIP, year) %>% 
  map(
    ~ggplot(data = .x,
            aes(x = temp_adjusted,
                y = depth,
                group = platform_cycle,
                col = double_extreme))+
      geom_path(data = .x %>% filter(double_extreme == 'N'),
                aes(x = temp_adjusted,
                    y = depth, 
                    group = platform_cycle,
                    col = double_extreme),
                size = 0.3)+
      geom_path(data = .x %>% filter(double_extreme == 'E'),
                aes(x = temp_adjusted,
                    y = depth, 
                    group = platform_cycle,
                    col = double_extreme),
                size = 0.5)+
      scale_y_reverse()+
      scale_color_manual(values = c('N' = 'gray', 'E' = 'red'))+
      facet_wrap(~month, ncol = 6)+
      labs(title = paste0('biome: ', unique(.x$biome_name), '| ', unique(.x$basin_AIP), '| ', unique(.x$year)),
           col = 'double extreme',
           x = 'Argo temperature',
           y = 'depth')
  )



```

## Pacific basin, STSS biome, December 2017

```{r pacific_STSS_dec_2017}

Pacific_STSS_2017 <- profile_double_extreme %>% 
  filter(date == '2017-12-15',
         basin_AIP == 'Pacific',
         biome_name == 'STSS')

# pH: 
Pacific_STSS_2017 %>% 
  ggplot()+
  geom_path(data = Pacific_STSS_2017 %>% filter(double_extreme == 'N'),
            aes(x = ph_in_situ_total_adjusted,
                y = depth,
                group = platform_cycle, 
                col = double_extreme),
            size = 0.3)+
  geom_path(data = Pacific_STSS_2017 %>% filter(double_extreme == 'E'),
            aes(x = ph_in_situ_total_adjusted,
                y = depth,
                group = platform_cycle, 
                col = double_extreme),
            size = 0.5)+
  scale_y_reverse()+
  scale_color_manual(values = c('E' = 'red', 'N' = 'grey'))+
  labs(title = 'Pacific, STSS biome, December 2017',
       col = 'double extreme',
       x = 'Argo pH',
       y = 'depth')

# Temperature 

Pacific_STSS_2017 %>% 
  ggplot()+
  geom_path(data = Pacific_STSS_2017 %>% filter(double_extreme == 'N'),
            aes(x = temp_adjusted,
                y = depth,
                group = platform_cycle, 
                col = double_extreme),
            size = 0.3)+
  geom_path(data = Pacific_STSS_2017 %>% filter(double_extreme == 'E'),
            aes(x = temp_adjusted,
                y = depth,
                group = platform_cycle, 
                col = double_extreme),
            size = 0.5)+
  scale_y_reverse()+
  scale_color_manual(values = c('E' = 'red', 'N' = 'grey'))+
  labs(title = 'Pacific, STSS biome, December 2017',
       col = 'double extreme',
       x = 'Argo pH',
       y = 'depth')

rm(Pacific_STSS_2017)
```

## Pacific basin, STSS biome, December 2019
 
No profiles for December 2019 in SPSS or STSS Pacific 

