---
title: "Argo pH Variability"
author: "Pasqualina Vonlanthen, David Stappard & Jens Daniel Müller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r set_options_global, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

# Task 

Explore the spatial variability of Argo pH profiles 

Dependencies
------------

pH_bgc_observed.rds - bgc preprocessed folder, created by ph_align_climatology. Not this file is written BEFORE the vertical alignment stage.

```{r load_libraries, include=FALSE}

library(tidyverse)
library(lubridate)
library(broom)
library(ggOceanMaps)
library(scico)
library(metR)
library(ggforce)
```

```{r set_global_theme}

theme_set(theme_bw())

```

# Load data 


```{r set_root_directories}

path_argo <- '/nfs/kryo/work/updata/bgc_argo_r_argodata'
path_argo_preprocessed <- paste0(path_argo, "/preprocessed_bgc_data")
path_emlr_utilities <- "/nfs/kryo/work/jenmueller/emlr_cant/utilities/files/"
path_updata <- '/nfs/kryo/work/updata'

path_argo <- '/nfs/kryo/work/datasets/ungridded/3d/ocean/floats/bgc_argo'
# /nfs/kryo/work/datasets/ungridded/3d/ocean/floats/bgc_argo/preprocessed_bgc_data
path_argo_preprocessed <- paste0(path_argo, "/preprocessed_bgc_data")

```

```{r load_data}

region_masks_all_1x1 <- read_rds(file = paste0(path_argo_preprocessed,
                                               "/region_masks_all_1x1.rds"))

region_masks_all_1x1 <- region_masks_all_1x1 %>%
  rename(biome = value) %>% 
  mutate(coast = as.character(coast))

# WOA 18 basin mask

basinmask <-
  read_csv(
    paste(path_emlr_utilities,
          "basin_mask_WOA18.csv",
          sep = ""),
    col_types = cols("MLR_basins" = col_character())
  )

basinmask <- basinmask %>%
  filter(MLR_basins == unique(basinmask$MLR_basins)[1]) %>% 
  select(-c(MLR_basins, basin))

# full argo data
# original_argo <- read_rds(file = paste0(path_argo_preprocessed, "/bgc_merge_pH_qc_1.rds"))

# change the date format for compatibility with OceanSODA data
# original_argo <- full_argo %>%
#   mutate(year = year(date),
#          month = month(date)) %>%
#   mutate(date = ymd(format(date, "%Y-%m-15")))

# full_argo <- read_rds(file = paste0(path_argo_preprocessed, '/bgc_merge_flag_AB.rds')) %>% 
#   select(-c(temp_adjusted:temp_adjusted_error, profile_temp_qc))
# 
# full_argo <- full_argo %>%
#   mutate(year = year(date),
#          month = month(date)) %>%
#   mutate(date = ymd(format(date, "%Y-%m-15")))

# load validated and vertically aligned pH profiles, 
full_argo <-
  read_rds(file = paste0(path_argo_preprocessed, "/pH_bgc_observed.rds")) %>%
  mutate(date = ymd(format(date, "%Y-%m-15")))

map <-
  read_rds(paste(path_emlr_utilities,
                 "map_landmask_WOA18.rds",
                 sep = ""))

```


# Regions 

### Biomes 

```{r filter_southern_ocean_open_ocean_biomes}

# keep only southern ocean biomes 

region_masks_all_1x1 <- region_masks_all_1x1 %>%
  filter(region == 'southern',
         biome != 0) %>% 
  select(-region)

# remove coastal data 

region_masks_all_1x1 <- region_masks_all_1x1 %>% 
  filter(coast == "0")
```

```{r map_of_biomes}

map +
  geom_tile(data = region_masks_all_1x1, 
            aes(x = lon, 
                y = lat, 
                fill = biome))+
  lims(y = c(-85, -30))+
  scale_fill_brewer(palette = 'Dark2')

```

### Basins

```{r filter_southern_ocean_basins}

basinmask <- basinmask %>%
  filter(lat < -30)
```

```{r map_of_basins, fig.asp=1}

map +
  geom_tile(data = basinmask, 
            aes(x = lon, 
                y = lat, 
                fill = basin_AIP))+
  lims(y = c(-85, -30))+
  scale_fill_brewer(palette = 'Dark2')
```


# Southern Ocean Argo pH 

```{r apply_region_and_basin_masks}

full_argo_SO <- inner_join(full_argo, region_masks_all_1x1)

full_argo_SO <- inner_join(full_argo_SO, basinmask)

# full_argo_SO <- full_argo_SO %>%
#   unite('platform_cycle', platform_number:cycle_number, sep = '_', remove = FALSE)

# original_argo_SO <- inner_join(original_argo, region_masks_all_1x1)
# 
# original_argo_SO <- inner_join(original_argo_SO, basinmask)
# 
# original_argo_SO <- original_argo_SO %>% 
#   unite('platform_cycle', platform_number:cycle_number, sep = '_', remove = FALSE)

```

## Profiles by longitude 

```{r plot_raw_pH_profiles_by_longitude}

# plot the argo temperature profiles according to their longitude, in each biome, basin, and year

full_argo_SO %>% 
  group_split(biome, basin_AIP, year) %>% 
  head(12) %>%
  map(
    ~ ggplot(data = .x,
             aes(x = ph_in_situ_total_adjusted,
                 y = depth,
                 group = file_id,
                 col = lon))+
      geom_path(data = .x,
                aes(x = ph_in_situ_total_adjusted,
                    y = depth,
                    group = file_id,
                    col = lon), 
                size = 0.3)+
      scale_y_reverse()+
      scale_color_viridis_c()+
      facet_wrap(~month, ncol = 6)+
      labs(title = paste0('biome: ', unique(.x$biome), '| basin: ', unique(.x$basin_AIP), ' |', unique(.x$year)),
           x = 'Argo pH',
           y = 'depth (m)',
           col = 'longitude')
  )
```


## Profiles by latitude 

```{r plot_raw_pH_profiles_by_latitude}

# color the argo profiles according to their latitude, for each biome, basin, and year 

full_argo_SO %>%
  group_split(biome, basin_AIP, year) %>%
  head(12) %>%
  map(
    ~ ggplot(data = .x,
             aes(x = ph_in_situ_total_adjusted,
                 y = depth,
                 group = file_id,
                 col = lat))+
      geom_path(data = .x,
                aes(x = ph_in_situ_total_adjusted,
                    y = depth,
                    group = file_id,
                    col = lat), 
                size = 0.3)+
      scale_y_reverse()+
      scale_color_viridis_c()+
      facet_wrap(~month, ncol = 6)+
      labs(title = paste0('biome: ', unique(.x$biome), '| basin: ', unique(.x$basin_AIP), ' |', unique(.x$year)),
           x = 'Argo pH',
           y = 'depth (m)',
           col = 'latitude')
  )


```

